In [1]:
import torch

# 创建tensor

In [2]:
#创建tensor
x = torch.empty(5,3)
print(x)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])


In [3]:
#创建随机tensor
x = torch.rand(5,3)
print(x)

tensor([[0.1788, 0.7309, 0.7310],
        [0.7712, 0.5126, 0.3541],
        [0.4170, 0.2819, 0.0045],
        [0.5601, 0.1818, 0.2677],
        [0.3670, 0.9997, 0.4974]])


In [4]:
#创建long型tensor
x = torch.zeros(5,3,dtype=torch.long)
print(x)
x.dtype

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


torch.int64

In [5]:
x = x.new_ones(5,3)
x.dtype
#与上一cell的x拥有相同的dtype

torch.int64

# tensor运算

In [6]:
#直接创建，叶子节点
x = torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [7]:
#加法创建y，拥有grad_fn
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
print(x.is_leaf,y.is_leaf)
#x是叶子节点，y不是叶子节点

True False


In [9]:
#来点复杂节点
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


输出z与z的平均值，grad_fn有响应的值

In [10]:
#requires_grad属性改变
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)#false
a.requires_grad_(True)
print(a.requires_grad)#true
b = (a*a).sum()
print(b.grad_fn)

False
True


# 梯度

In [11]:
#out反向求导
out.backward()

F:\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py:149: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:115.)
  allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag


In [12]:
#out对x的导数
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [14]:
out2 = x.sum()
out2.backward()
print(x.grad)
#注意grad是累加的

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [15]:
out3 = x.sum()
x.grad.data.zero_() #x梯度清零
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


# tensor操作

In [24]:
x = torch.randn(5,3)
print(x)#create tensor
y = x.view(3,5)#change the shape
print(y)
z = x.view(-1) #chage the shape
print(z)
p = x.view(-1,5)#change the shape
print(p)
#attention:共享内存，一个改变以上都会改变

tensor([[ 0.9180,  1.8064, -0.1352],
        [-0.3963,  0.3627, -0.1040],
        [-1.0239,  1.0451, -1.3425],
        [ 2.4770, -1.7507,  0.1319],
        [-0.1877, -1.1436,  1.0243]])
tensor([[ 0.9180,  1.8064, -0.1352, -0.3963,  0.3627],
        [-0.1040, -1.0239,  1.0451, -1.3425,  2.4770],
        [-1.7507,  0.1319, -0.1877, -1.1436,  1.0243]])
tensor([ 0.9180,  1.8064, -0.1352, -0.3963,  0.3627, -0.1040, -1.0239,  1.0451,
        -1.3425,  2.4770, -1.7507,  0.1319, -0.1877, -1.1436,  1.0243])
tensor([[ 0.9180,  1.8064, -0.1352, -0.3963,  0.3627],
        [-0.1040, -1.0239,  1.0451, -1.3425,  2.4770],
        [-1.7507,  0.1319, -0.1877, -1.1436,  1.0243]])


In [25]:
y += 1
print(x)
print(y)
#共享内存

tensor([[ 1.9180,  2.8064,  0.8648],
        [ 0.6037,  1.3627,  0.8960],
        [-0.0239,  2.0451, -0.3425],
        [ 3.4770, -0.7507,  1.1319],
        [ 0.8123, -0.1436,  2.0243]])
tensor([[ 1.9180,  2.8064,  0.8648,  0.6037,  1.3627],
        [ 0.8960, -0.0239,  2.0451, -0.3425,  3.4770],
        [-0.7507,  1.1319,  0.8123, -0.1436,  2.0243]])


In [26]:
#那么不共享内存应该怎么做
y = x.clone().view(15)
y += 1
print(x)
print(y)

tensor([[ 1.9180,  2.8064,  0.8648],
        [ 0.6037,  1.3627,  0.8960],
        [-0.0239,  2.0451, -0.3425],
        [ 3.4770, -0.7507,  1.1319],
        [ 0.8123, -0.1436,  2.0243]])
tensor([2.9180, 3.8064, 1.8648, 1.6037, 2.3627, 1.8960, 0.9761, 3.0451, 0.6575,
        4.4770, 0.2493, 2.1319, 1.8123, 0.8564, 3.0243])


In [27]:
#item() tensor->python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1800])
0.17995275557041168


pytorch 其他线性函数 <br />
trace -> 对角线之和（矩阵的秩）<br />
diag  -> 对角线元素<br />
triu/tril -> 上三角/下三角<br />
mm/bmm -> 矩阵乘法，batch乘法运算<br />
addmm/addbmm/addmv/addmv/addr/badbmm -> 矩阵运算<br />
t -> 转置<br />
dot/class -> 内积/外积<br />
inverse -> 求逆矩阵<br />
svd -> 奇异值分解<br />

# 广播机制

In [41]:
#何为广播：将数据按一定规律扩增,有元素被复制
x = torch.arange(1,5,dtype = torch.int).view(-1,4)
y = torch.ones(4,dtype=torch.int).view(4,1)
print(x)
print(y)
print(x+y)


tensor([[1, 2, 3, 4]], dtype=torch.int32)
tensor([[1],
        [1],
        [1],
        [1]], dtype=torch.int32)
tensor([[2, 3, 4, 5],
        [2, 3, 4, 5],
        [2, 3, 4, 5],
        [2, 3, 4, 5]], dtype=torch.int32)


In [44]:
print(x.size())
print(y.size())
print(x*y)
print(torch.mm(y,x))

torch.Size([1, 4])
torch.Size([4, 1])
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]], dtype=torch.int32)
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]], dtype=torch.int32)


# 内存开销

In [45]:
#内存开销
#y = x + y 为新的y开辟了新内存
x = torch.tensor([3,4])
y = torch.tensor([5,6])
id_before = id(y)
y = x + y
print("id_before:",id_before)
print("id",id(y))

id_before: 1808853909440
id 1808853909008


In [47]:
#那么如何覆盖y原来的内存呢
#方法一
x = torch.tensor([3,4])
y = torch.tensor([5,6])
id_before = id(y)
y.add_(x)
print("id_before:",id_before)
print("id",id(y))
print(x)
print(y)

id_before: 1808862866024
id 1808862866024
tensor([3, 4])
tensor([ 8, 10])


In [49]:
#那么如何覆盖y原来的内存呢
#方法
x = torch.tensor([3,4])
y = torch.tensor([5,6])
id_before = id(y)
torch.add(x,y,out=y)#等效于y+=x,y.add_(x)
print("id_before:",id_before)
print("id",id(y))
print(x)
print(y)

id_before: 1808856324928
id 1808856324928
tensor([3, 4])
tensor([ 8, 10])


# tensor 与 numpy 相互转换

In [50]:
#tensor->numpy
a = torch.ones(4,5)
b = a.numpy()
print(a,b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
a += 1
print(a,b)
b+=1
print(a,b)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]) [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


仍然共享内存

In [53]:
#numpy->tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
a+=1
print(a,b)
b+=1
print(a,b)
#共享内存

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [55]:
#如何不共享内存,创建新tensor->torch.tensor()
c = torch.tensor(a)
a+=1
print(a,c)

[5. 5. 5. 5. 5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


# tensor on GPU

In [56]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)  #直接创建一个在GPU上的tensor
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))